#ifndef SOLIDSYSLOGSERVICESTATUS_H
#define SOLIDSYSLOGSERVICESTATUS_H

enum SolidSyslogServiceStatus
{
    SOLIDSYSLOG_SERVICE_IDLE,
    SOLIDSYSLOG_SERVICE_READY,
    SOLIDSYSLOG_SERVICE_BLOCKED,
    SOLIDSYSLOG_SERVICE_HALTED
};

#endif /* SOLIDSYSLOGSERVICESTATUS_H */
