/* SPDX-FileCopyrightText: Copyright 2026 Cozens Software Solutions Limited
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0 OR LicenseRef-PolyForm-Internal-Use-1.0.0 OR LicenseRef-COSOSO-Commercial
 */

/* The VIP compiles this file with its own flags, which select C89, so it stands
 * in for an application: vxWorks.h first, as Wind River code includes it, then
 * every public header of Core and the VxWorks64 pack. It proves they compile
 * there; the BDD target itself is C99 and is built beside the library. */

#include "vxWorks.h"

#include "SolidSyslog.h"
#include "SolidSyslogAddress.h"
#include "SolidSyslogAddressErrors.h"
#include "SolidSyslogAesGcmPolicyErrors.h"
#include "SolidSyslogAtomicCounter.h"
#include "SolidSyslogAtomicCounterDefinition.h"
#include "SolidSyslogAtomicCounterErrors.h"
#include "SolidSyslogBlockDevice.h"
#include "SolidSyslogBlockDeviceDefinition.h"
#include "SolidSyslogBlockStore.h"
#include "SolidSyslogBlockStoreErrors.h"
#include "SolidSyslogBuffer.h"
#include "SolidSyslogBufferCategories.h"
#include "SolidSyslogBufferDefinition.h"
#include "SolidSyslogCircularBuffer.h"
#include "SolidSyslogCircularBufferErrors.h"
#include "SolidSyslogConfig.h"
#include "SolidSyslogConfigLock.h"
#include "SolidSyslogCrc16.h"
#include "SolidSyslogCrc16Policy.h"
#include "SolidSyslogDatagram.h"
#include "SolidSyslogDatagramDefinition.h"
#include "SolidSyslogDatagramErrors.h"
#include "SolidSyslogEndpoint.h"
#include "SolidSyslogEndpointHost.h"
#include "SolidSyslogError.h"
#include "SolidSyslogErrorCategory.h"
#include "SolidSyslogErrors.h"
#include "SolidSyslogExternC.h"
#include "SolidSyslogFile.h"
#include "SolidSyslogFileBlockDevice.h"
#include "SolidSyslogFileBlockDeviceErrors.h"
#include "SolidSyslogFileDefinition.h"
#include "SolidSyslogFileErrors.h"
#include "SolidSyslogHeaderField.h"
#include "SolidSyslogHeaderFieldFunction.h"
#include "SolidSyslogHmacSha256PolicyErrors.h"
#include "SolidSyslogKeyFunction.h"
#include "SolidSyslogMetaSd.h"
#include "SolidSyslogMetaSdErrors.h"
#include "SolidSyslogMutex.h"
#include "SolidSyslogMutexDefinition.h"
#include "SolidSyslogMutexErrors.h"
#include "SolidSyslogNullAtomicCounter.h"
#include "SolidSyslogNullBlockDevice.h"
#include "SolidSyslogNullBuffer.h"
#include "SolidSyslogNullDatagram.h"
#include "SolidSyslogNullFile.h"
#include "SolidSyslogNullMutex.h"
#include "SolidSyslogNullResolver.h"
#include "SolidSyslogNullSd.h"
#include "SolidSyslogNullSecurityPolicy.h"
#include "SolidSyslogNullSender.h"
#include "SolidSyslogNullStore.h"
#include "SolidSyslogNullStream.h"
#include "SolidSyslogOriginSd.h"
#include "SolidSyslogOriginSdErrors.h"
#include "SolidSyslogPassthroughBuffer.h"
#include "SolidSyslogPassthroughBufferErrors.h"
#include "SolidSyslogPrival.h"
#include "SolidSyslogResolver.h"
#include "SolidSyslogResolverCategories.h"
#include "SolidSyslogResolverDefinition.h"
#include "SolidSyslogResolverErrors.h"
#include "SolidSyslogSdElement.h"
#include "SolidSyslogSdValue.h"
#include "SolidSyslogSdValueFunction.h"
#include "SolidSyslogSecurityPolicyCategories.h"
#include "SolidSyslogSecurityPolicyDefinition.h"
#include "SolidSyslogSender.h"
#include "SolidSyslogSenderCategories.h"
#include "SolidSyslogSenderDefinition.h"
#include "SolidSyslogServiceStatus.h"
#include "SolidSyslogSleep.h"
#include "SolidSyslogStore.h"
#include "SolidSyslogStoreDefinition.h"
#include "SolidSyslogStream.h"
#include "SolidSyslogStreamCategories.h"
#include "SolidSyslogStreamDefinition.h"
#include "SolidSyslogStreamSender.h"
#include "SolidSyslogStreamSenderErrors.h"
#include "SolidSyslogStructuredData.h"
#include "SolidSyslogStructuredDataDefinition.h"
#include "SolidSyslogSwitchingSender.h"
#include "SolidSyslogSwitchingSenderErrors.h"
#include "SolidSyslogTcpConnectTimeoutFunction.h"
#include "SolidSyslogTcpStreamErrors.h"
#include "SolidSyslogTimeQuality.h"
#include "SolidSyslogTimeQualitySd.h"
#include "SolidSyslogTimeQualitySdErrors.h"
#include "SolidSyslogTimestamp.h"
#include "SolidSyslogTlsCredentialsErrors.h"
#include "SolidSyslogTlsCredentialsInstalled.h"
#include "SolidSyslogTlsFingerprint.h"
#include "SolidSyslogTlsHandshakeTimeoutFunction.h"
#include "SolidSyslogTlsStreamCategories.h"
#include "SolidSyslogTlsStreamErrors.h"
#include "SolidSyslogTransport.h"
#include "SolidSyslogTunables.h"
#include "SolidSyslogTunablesDefaults.h"
#include "SolidSyslogUdpPayload.h"
#include "SolidSyslogUdpSender.h"
#include "SolidSyslogUdpSenderErrors.h"
#include "SolidSyslogVxWorks64Address.h"
#include "SolidSyslogVxWorks64AddressErrors.h"
#include "SolidSyslogVxWorks64AtomicCounter.h"
#include "SolidSyslogVxWorks64AtomicCounterErrors.h"
#include "SolidSyslogVxWorks64Clock.h"
#include "SolidSyslogVxWorks64Datagram.h"
#include "SolidSyslogVxWorks64DatagramErrors.h"
#include "SolidSyslogVxWorks64Hostname.h"
#include "SolidSyslogVxWorks64Mutex.h"
#include "SolidSyslogVxWorks64MutexErrors.h"
#include "SolidSyslogVxWorks64Resolver.h"
#include "SolidSyslogVxWorks64ResolverErrors.h"
#include "SolidSyslogVxWorks64Sleep.h"
#include "SolidSyslogVxWorks64SysUpTime.h"
#include "SolidSyslogVxWorks64TcpStream.h"
#include "SolidSyslogVxWorks64TcpStreamErrors.h"

/* ISO C requires a translation unit to declare something of its own. */
extern int BddTargetVxWorks64Headers_Compiled;
