#include "SolidSyslogPrival.h"
#include "CppUTest/TestHarness.h"

TEST_GROUP(SolidSyslogPrival){};

TEST(SolidSyslogPrival, FacilityEnumValuesMatchRfc5424)
{
    LONGS_EQUAL(0, SOLIDSYSLOG_FACILITY_KERN);
    LONGS_EQUAL(1, SOLIDSYSLOG_FACILITY_USER);
    LONGS_EQUAL(2, SOLIDSYSLOG_FACILITY_MAIL);
    LONGS_EQUAL(3, SOLIDSYSLOG_FACILITY_DAEMON);
    LONGS_EQUAL(4, SOLIDSYSLOG_FACILITY_AUTH);
    LONGS_EQUAL(5, SOLIDSYSLOG_FACILITY_SYSLOG);
    LONGS_EQUAL(6, SOLIDSYSLOG_FACILITY_LPR);
    LONGS_EQUAL(7, SOLIDSYSLOG_FACILITY_NEWS);
    LONGS_EQUAL(8, SOLIDSYSLOG_FACILITY_UUCP);
    LONGS_EQUAL(9, SOLIDSYSLOG_FACILITY_CRON);
    LONGS_EQUAL(10, SOLIDSYSLOG_FACILITY_AUTHPRIV);
    LONGS_EQUAL(11, SOLIDSYSLOG_FACILITY_FTP);
    LONGS_EQUAL(12, SOLIDSYSLOG_FACILITY_NTP);
    LONGS_EQUAL(13, SOLIDSYSLOG_FACILITY_AUDIT);
    LONGS_EQUAL(14, SOLIDSYSLOG_FACILITY_ALERT);
    LONGS_EQUAL(15, SOLIDSYSLOG_FACILITY_CLOCK);
    LONGS_EQUAL(16, SOLIDSYSLOG_FACILITY_LOCAL0);
    LONGS_EQUAL(17, SOLIDSYSLOG_FACILITY_LOCAL1);
    LONGS_EQUAL(18, SOLIDSYSLOG_FACILITY_LOCAL2);
    LONGS_EQUAL(19, SOLIDSYSLOG_FACILITY_LOCAL3);
    LONGS_EQUAL(20, SOLIDSYSLOG_FACILITY_LOCAL4);
    LONGS_EQUAL(21, SOLIDSYSLOG_FACILITY_LOCAL5);
    LONGS_EQUAL(22, SOLIDSYSLOG_FACILITY_LOCAL6);
    LONGS_EQUAL(23, SOLIDSYSLOG_FACILITY_LOCAL7);
}

TEST(SolidSyslogPrival, SeverityEnumValuesMatchRfc5424)
{
    LONGS_EQUAL(0, SolidSyslogSeverity_Emergency);
    LONGS_EQUAL(1, SolidSyslogSeverity_Alert);
    LONGS_EQUAL(2, SolidSyslogSeverity_Critical);
    LONGS_EQUAL(3, SolidSyslogSeverity_Error);
    LONGS_EQUAL(4, SolidSyslogSeverity_Warning);
    LONGS_EQUAL(5, SolidSyslogSeverity_Notice);
    LONGS_EQUAL(6, SolidSyslogSeverity_Informational);
    LONGS_EQUAL(7, SolidSyslogSeverity_Debug);
}
