#ifndef BDDTARGETSTDERRERRORHANDLER_H
#define BDDTARGETSTDERRERRORHANDLER_H

#include "SolidSyslogExternC.h"

SOLIDSYSLOG_EXTERN_C_BEGIN

    void BddTargetStderrErrorHandler_Install(void);

SOLIDSYSLOG_EXTERN_C_END

#endif /* BDDTARGETSTDERRERRORHANDLER_H */
