"""MkDocs build hook: drop the Doxygen kind from generated member headings.

mkdoxy titles every member with its kind, so a page reads ``function
SolidSyslogFile_Close``, ``define SOLIDSYSLOG_FILE_POOL_SIZE``, ``variable
Acquire`` — and its table of contents repeats the word once per member. The
kind says nothing the page has not already said: each of these sections is
titled by kind (*Public Functions Documentation*, *Macro Definition
Documentation*), so everything in it is of that kind.

The heading text is what MkDocs turns into the anchor, so dropping a word from
it would move every anchor on the page and silently break the links that point
there. Those links exist, inside the site and outside it: mkdoxy links header
and directory pages at the members they declare, two hand-written pages link to
``#function-…``, and so does the product page on the company website. Nothing
validates a link pointing *into* the site, so the breakage would not surface.

Each heading therefore keeps the anchor it had, stated explicitly. The anchor
is not reconstructed by rule — it is generated by calling the same slugify the
site configures for ``toc``, so it matches whatever that would have produced.

An anonymous enum is left alone. Doxygen names it ``@0``, and a heading reading
``@0`` is worse than one reading ``enum @0``.
"""

import os
import re

from pymdownx.slugs import slugify

# The `toc` slugify from mkdocs.yml. Calling it is what guarantees the anchor
# below is the one MkDocs built from the heading before this hook touched it.
SLUGIFY = slugify(case="lower")

KINDS = ("function", "define", "enum", "typedef", "variable")

MEMBER_HEADING = re.compile(
    r"^### (?P<kind>" + "|".join(KINDS) + r") (?P<name>(?!@)\S.*?)[ \t]*$",
    re.MULTILINE,
)

GENERATED_PREFIX = "api/"


def _retitle(match):
    """The member's own name, keeping the anchor its kind-prefixed title had."""
    anchor = SLUGIFY(match.group("kind") + " " + match.group("name"), "-")
    return "### " + match.group("name") + " { #" + anchor + " }"


def on_page_markdown(markdown, page, config, files, **kwargs):
    src = getattr(page.file, "src_uri", None) or page.file.src_path.replace(os.sep, "/")
    if not src.startswith(GENERATED_PREFIX):
        return markdown
    return MEMBER_HEADING.sub(_retitle, markdown)
