#ifndef SOLIDSYSLOGMBEDTLSHMACSHA256POLICYERRORS_H
#define SOLIDSYSLOGMBEDTLSHMACSHA256POLICYERRORS_H

#include "ExternC.h"

EXTERN_C_BEGIN

    struct SolidSyslogErrorSource;

    enum SolidSyslogMbedTlsHmacSha256PolicyErrors
    {
        MBEDTLSHMACSHA256POLICY_ERROR_POOL_EXHAUSTED,
        MBEDTLSHMACSHA256POLICY_ERROR_UNKNOWN_DESTROY,
        MBEDTLSHMACSHA256POLICY_ERROR_BAD_CONFIG,
        MBEDTLSHMACSHA256POLICY_ERROR_KEY_UNAVAILABLE,
        MBEDTLSHMACSHA256POLICY_ERROR_KEY_TOO_SHORT,
        MBEDTLSHMACSHA256POLICY_ERROR_HMAC_FAILED,
        MBEDTLSHMACSHA256POLICY_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource MbedTlsHmacSha256PolicyErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGMBEDTLSHMACSHA256POLICYERRORS_H */
