# Integration manifest generator (S30.03).
#
# Emits the file / include-dir / -D manifest a NON-CMake integrator (IAR / Keil /
# MPLAB / CCS / hand Makefile) needs to compile SolidSyslog into their own
# project. The .c file lists are read straight from the build targets — the Core
# library's SOURCES and each selected pack's INTERFACE_SOURCES (populated in
# S30.02) — so the manifest can never drift from what the packs actually ship.
#
# Selection: SOLIDSYSLOG_MANIFEST_PACKS is a ;-list of pack short-names (without
# the SolidSyslog:: prefix), e.g. "LwipRaw;LwipRawDnsResolver;MbedTls;FreeRtos;FatFs".
# Empty (the default) means "every SolidSyslog::<Pack> target that this configure
# defined". Core is always included.
#
# Output: written to ${CMAKE_BINARY_DIR}/solidsyslog-manifest.txt at configure
# time, and printed by `cmake --build <dir> --target manifest`. If
# SOLIDSYSLOG_MANIFEST_OUTPUT is set it is ALSO written there (used to refresh the
# committed docs/generated sample, which CI diff-checks for drift).

set(SOLIDSYSLOG_MANIFEST_PACKS "" CACHE STRING
    "Packs to include in the generated integration manifest (;-list of short \
names without the SolidSyslog:: prefix). Empty = all defined packs.")
set(SOLIDSYSLOG_MANIFEST_OUTPUT "" CACHE FILEPATH
    "Optional extra path to also write the generated manifest to (e.g. the \
committed docs/generated sample).")

# Every pack the generator knows about, in manifest display order. Each carries
# the integrator-supplied config header(s) that pack requires (stable knowledge;
# the volatile .c lists come from the targets, not from here).
set(_SOLIDSYSLOG_MANIFEST_KNOWN_PACKS
    FreeRtos PlusTcp LwipRaw LwipRawDnsResolver MbedTls FatFs PlusFat)
set(_SOLIDSYSLOG_MANIFEST_CFG_FreeRtos           "FreeRTOSConfig.h")
set(_SOLIDSYSLOG_MANIFEST_CFG_PlusTcp            "FreeRTOSConfig.h, FreeRTOSIPConfig.h")
set(_SOLIDSYSLOG_MANIFEST_CFG_LwipRaw            "lwipopts.h")
set(_SOLIDSYSLOG_MANIFEST_CFG_LwipRawDnsResolver "lwipopts.h (with LWIP_DNS=1)")
set(_SOLIDSYSLOG_MANIFEST_CFG_MbedTls            "mbedtls_config.h")
set(_SOLIDSYSLOG_MANIFEST_CFG_FatFs              "ffconf.h")
set(_SOLIDSYSLOG_MANIFEST_CFG_PlusFat            "FreeRTOSFATConfig.h")

# Make an absolute path repo-relative for display; pass others through unchanged.
function(_solidsyslog_manifest_relpath OUT_VAR PATH)
    set(_p "${PATH}")
    if(IS_ABSOLUTE "${_p}")
        file(RELATIVE_PATH _p "${CMAKE_SOURCE_DIR}" "${_p}")
    endif()
    set(${OUT_VAR} "${_p}" PARENT_SCOPE)
endfunction()

# Append the .c sources of an INTERFACE pack target (repo-relative) to OUT_VAR.
function(_solidsyslog_manifest_pack_sources OUT_VAR TARGET)
    set(_lines "")
    get_target_property(_srcs "${TARGET}" INTERFACE_SOURCES)
    if(_srcs)
        foreach(_s ${_srcs})
            _solidsyslog_manifest_relpath(_rel "${_s}")
            string(APPEND _lines "${_rel}\n")
        endforeach()
    endif()
    set(${OUT_VAR} "${_lines}" PARENT_SCOPE)
endfunction()

function(solidsyslog_generate_manifest)
    # Resolve the selection: explicit list, else every known pack that exists.
    set(_selected "")
    if(SOLIDSYSLOG_MANIFEST_PACKS)
        set(_selected ${SOLIDSYSLOG_MANIFEST_PACKS})
    else()
        foreach(_pack ${_SOLIDSYSLOG_MANIFEST_KNOWN_PACKS})
            if(TARGET SolidSyslog::${_pack})
                list(APPEND _selected ${_pack})
            endif()
        endforeach()
    endif()

    string(REPLACE ";" ", " _selected_display "${_selected}")
    if(NOT _selected_display)
        set(_selected_display "(none — Core only)")
    endif()

    # --- Header ---------------------------------------------------------------
    set(_m "# SolidSyslog integration manifest — GENERATED by CMake (S30.03).\n")
    string(APPEND _m "# Do not edit by hand. Regenerate with: cmake --build <build-dir> --target manifest\n")
    string(APPEND _m "# Selected packs: ${_selected_display}\n")
    string(APPEND _m "#\n")
    string(APPEND _m "# A non-CMake integrator (IAR / Keil / MPLAB / CCS / Make) compiles the .c\n")
    string(APPEND _m "# files below, with the include dirs on the compiler path, against their own\n")
    string(APPEND _m "# config headers. See docs/getting-started.md for the walkthrough.\n\n")

    # --- Source files ---------------------------------------------------------
    string(APPEND _m "## Source files (.c) — compile all of these\n\n")
    string(APPEND _m "# Core (always required):\n")
    get_target_property(_core_srcs SolidSyslog SOURCES)
    foreach(_s ${_core_srcs})
        if(IS_ABSOLUTE "${_s}")
            # The host Pattern-A adapters (Posix / Windows / OpenSSL / C11 atomics)
            # are baked into the Core target by CMake auto-detect. They are
            # host-build conveniences and have no place in a (cross / embedded)
            # integration manifest — keep only the portable Core/Source set.
            string(FIND "${_s}" "/Core/Source/" _in_core)
            if(_in_core EQUAL -1)
                continue()
            endif()
            _solidsyslog_manifest_relpath(_rel "${_s}")
        else()
            set(_rel "Core/Source/${_s}")
        endif()
        string(APPEND _m "${_rel}\n")
    endforeach()

    foreach(_pack ${_selected})
        if(NOT TARGET SolidSyslog::${_pack})
            message(WARNING
                "Manifest: SolidSyslog::${_pack} is not a defined target in this "
                "configuration; skipping. (Is its upstream env path set?)")
        else()
            string(APPEND _m "\n# ${_pack}:\n")
            _solidsyslog_manifest_pack_sources(_pack_srcs SolidSyslog::${_pack})
            string(APPEND _m "${_pack_srcs}")
        endif()
    endforeach()

    # --- Include directories --------------------------------------------------
    string(APPEND _m "\n## Include directories\n\n")
    set(_incdirs "Core/Interface" "Core/Source")
    foreach(_pack ${_selected})
        if(TARGET SolidSyslog::${_pack})
            get_target_property(_incs SolidSyslog::${_pack} INTERFACE_INCLUDE_DIRECTORIES)
            if(_incs)
                foreach(_i ${_incs})
                    _solidsyslog_manifest_relpath(_rel "${_i}")
                    list(APPEND _incdirs "${_rel}")
                endforeach()
            endif()
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _incdirs)
    foreach(_d ${_incdirs})
        string(APPEND _m "${_d}\n")
    endforeach()
    string(APPEND _m "# Plus, located in YOUR project: the upstream library include dirs (lwIP,\n")
    string(APPEND _m "# Mbed TLS, FreeRTOS, FatFs) and the directory holding your config headers.\n")

    # --- Required defines -----------------------------------------------------
    string(APPEND _m "\n## Required defines\n\n")
    string(APPEND _m "-DSOLIDSYSLOG_USER_TUNABLES_FILE=\"my_tunables.h\"   # your tunable overrides (optional)\n")
    list(FIND _selected "LwipRawDnsResolver" _has_dns)
    if(NOT _has_dns EQUAL -1)
        string(APPEND _m "-DLWIP_DNS=1                                         # required by SolidSyslog::LwipRawDnsResolver\n")
    endif()
    list(FIND _selected "MbedTls" _has_mbedtls)
    if(NOT _has_mbedtls EQUAL -1)
        string(APPEND _m "# Mbed TLS: point MBEDTLS_USER_CONFIG_FILE (or MBEDTLS_CONFIG_FILE) at your mbedtls config,\n")
        string(APPEND _m "#           and use the SAME config when building the mbedTLS library itself.\n")
    endif()

    # --- Config headers you supply --------------------------------------------
    string(APPEND _m "\n## Integrator-supplied config headers\n\n")
    foreach(_pack ${_selected})
        set(_cfg "${_SOLIDSYSLOG_MANIFEST_CFG_${_pack}}")
        if(_cfg)
            string(APPEND _m "${_cfg}   (${_pack})\n")
        endif()
    endforeach()

    # --- Emit -----------------------------------------------------------------
    set(_out "${CMAKE_BINARY_DIR}/solidsyslog-manifest.txt")
    file(WRITE "${_out}" "${_m}")
    set(SOLIDSYSLOG_MANIFEST_FILE "${_out}" CACHE INTERNAL "Generated manifest path")
    if(SOLIDSYSLOG_MANIFEST_OUTPUT)
        file(WRITE "${SOLIDSYSLOG_MANIFEST_OUTPUT}" "${_m}")
        message(STATUS "Manifest also written to ${SOLIDSYSLOG_MANIFEST_OUTPUT}")
    endif()

    # `cmake --build <dir> --target manifest` prints the generated file.
    if(NOT TARGET manifest)
        add_custom_target(manifest
            COMMAND ${CMAKE_COMMAND} -DSOLIDSYSLOG_MANIFEST_FILE=${_out}
                    -P ${CMAKE_SOURCE_DIR}/cmake/PrintManifest.cmake
            VERBATIM
            COMMENT "SolidSyslog integration manifest (${_selected_display})")
    endif()
endfunction()
