#ifndef SOLIDSYSLOGPOSIXMESSAGEQUEUEBUFFERERRORS_H
#define SOLIDSYSLOGPOSIXMESSAGEQUEUEBUFFERERRORS_H

#include "ExternC.h"
#include "SolidSyslogError.h"

EXTERN_C_BEGIN

    enum SolidSyslogPosixMessageQueueBufferErrors
    {
        POSIXMESSAGEQUEUEBUFFER_ERROR_POOL_EXHAUSTED,
        POSIXMESSAGEQUEUEBUFFER_ERROR_UNKNOWN_DESTROY,
        POSIXMESSAGEQUEUEBUFFER_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource PosixMessageQueueBufferErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGPOSIXMESSAGEQUEUEBUFFERERRORS_H */
