#ifndef SOLIDSYSLOGTLSSTREAMERRORS_H
#define SOLIDSYSLOGTLSSTREAMERRORS_H

#include "ExternC.h"

EXTERN_C_BEGIN

    struct SolidSyslogErrorSource;

    enum SolidSyslogTlsStreamErrors
    {
        TLSSTREAM_ERROR_POOL_EXHAUSTED,
        TLSSTREAM_ERROR_UNKNOWN_DESTROY,
        TLSSTREAM_ERROR_CONTEXT_INIT_FAILED,
        TLSSTREAM_ERROR_SESSION_INIT_FAILED,
        TLSSTREAM_ERROR_SERVER_NAME_NOT_SET,
        TLSSTREAM_ERROR_HANDSHAKE_REJECTED,
        TLSSTREAM_ERROR_HANDSHAKE_TIMEOUT,
        TLSSTREAM_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource TlsStreamErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGTLSSTREAMERRORS_H */
