#ifndef SOLIDSYSLOGOPENSSLHMACSHA256POLICYERRORS_H
#define SOLIDSYSLOGOPENSSLHMACSHA256POLICYERRORS_H

#include "ExternC.h"

EXTERN_C_BEGIN

    struct SolidSyslogErrorSource;

    enum SolidSyslogOpenSslHmacSha256PolicyErrors
    {
        OPENSSLHMACSHA256POLICY_ERROR_POOL_EXHAUSTED,
        OPENSSLHMACSHA256POLICY_ERROR_UNKNOWN_DESTROY,
        OPENSSLHMACSHA256POLICY_ERROR_BAD_CONFIG,
        OPENSSLHMACSHA256POLICY_ERROR_KEY_UNAVAILABLE,
        OPENSSLHMACSHA256POLICY_ERROR_KEY_TOO_SHORT,
        OPENSSLHMACSHA256POLICY_ERROR_HMAC_FAILED,
        OPENSSLHMACSHA256POLICY_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource OpenSslHmacSha256PolicyErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGOPENSSLHMACSHA256POLICYERRORS_H */
